-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 19:23:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mini_chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mini_chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mini_chat` DEFAULT CHARACTER SET utf8 ;
USE `mini_chat` ;

-- -----------------------------------------------------
-- Table `mini_chat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_chat`.`users` (
  `id_user` INT NOT NULL,
  `profil` VARCHAR(255) NULL DEFAULT NULL,
  `pseudo` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `join_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `pseudo_UNIQUE` (`pseudo` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `mini_chat`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_chat`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_chat`.`conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_chat`.`conversations` (
  `id_conversation` INT NOT NULL,
  `title` VARCHAR(255) NULL,
  PRIMARY KEY (`id_conversation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_chat`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mini_chat`.`messages` (
  `id_message` INT NOT NULL,
  `content` TEXT NULL,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  `conversation_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_message`),
  INDEX `fk_messages_conversations_idx` (`conversation_id` ASC) VISIBLE,
  INDEX `fk_messages_users1_idx` (`receiver_id` ASC) VISIBLE,
  INDEX `fk_messages_users2_idx` (`sender_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
